version: 0.2

run-as: builder

phases:
  pre_build:
    on-failure: ABORT
    commands:
      # change ownership of mounted EFS volumes
      - sudo chown builder:builder /mnt/yocto_cache/dl_dir /mnt/yocto_cache/sstate_cache
      - whoami
      - ls -la /mnt/yocto_cache/dl_dir
      - ls -la /mnt/yocto_cache/sstate_cache
      # set target images
      - export images="$(for i in ${IMAGES}; do echo -n "mc:${MULTI_CONF}:${i} "; done)"
      # extract kas artifact
      - tar -xf kas.tar
      - rm kas.tar
      # clone meta repos
      - kas shell --update -c "exit" kas-irma6-base.yml
      # checkout branches with same name, if exists
      - for i in ${LAYERS}; do (cd ${LAYERS}; git checkout "${BRANCH_NAME}" || true); done

  build:
    on-failure: ABORT
    commands:
      # build images
      - kas shell -k -c "bitbake ${images}" kas-irma6-base.yml:include/kas-irma6-jenkins-develop.yml
