version: 0.2

run-as: builder

phases:
  pre_build:
    on-failure: ABORT
    commands:
      # Generate list of targets from string
      - export targets="$(for i in ${MULTI_CONFS}; do echo -n "mc:${i}:irma6-base "; done)"

  build:
    on-failure: ABORT
    commands:
      # Fetch base sources for all targets
      - kas shell --update -c "bitbake ${targets} --runonly=fetch" kas-irma6-base.yml:include/kas-irma6-jenkins-release-fetch.yml

  post_build:
    on-failure: ABORT
    commands:
      # rsync dl-dir to pre-mirror location for future use. Exclude shallow git archives
      - sudo rsync -avh --exclude=build/dl_dir/git2_* build/dl_dir/ /mnt/yocto_cache/dl_dir/
      # remove unnecessary files for archiving
      - rm -rf build/tmp build/dl_dir/git2/
      # Create a tar archive containing the complete build environment while preserving file permissions
      - touch ${GIT_TAG}-base-sources.tar
      - tar --exclude=${GIT_TAG}-base-sources.tar -cf ${GIT_TAG}-base-sources.tar .

artifacts:
  files:
    - "${GIT_TAG}-base-sources.tar"
    - "buildspecs/**/*"
