version: 0.2

run-as: builder

phases:
  pre_build:
    on-failure: ABORT
    commands:
      # extract base-sources from fetch stage
      - tar -xf ${GIT_TAG}-base-sources.tar
      - rm ${GIT_TAG}-base-sources.tar

  build:
    on-failure: ABORT
    commands:
      # build base images, cleanup on failure
      - kas shell -c "bitbake mc:${MULTI_CONF}:irma6-base" kas-irma6-base.yml:include/kas-irma6-jenkins-release.yml:include/kas-offline-build.yml
